### ISSUE TITLE
FR14: Dog's Administration panel

### ISSUE THREAD

**Issue by Emanuelpa** [EvelynZapata20/DoggyCare#13]
**Description**: The system shall provide the vet with the ability to edit dog’s information through an administration panel.

**Acceptance Criteria**:

- The vet can click on any patient and will be redirected to the "Dog profile" window.
- The veterinarian must be able to edit all the fields corresponding to the dog (image, name, owner, age, breed, gender, weight)
- The window should contain three buttons, one to delete patient, another to save changes and a last one to cancel.
- If the vet presses delete dog, a confirmation form will be sent to ensure their intention to delete the dog. Once they confirm their intention by submitting the form, the dog will be deleted from the database.
- If the vet presses cancel, they will be redirected to the "patients" tab.
- If the vet presses save changes, all changes recorded in the database will be edited.

**Tasks**:

- [x] Create the interface with the elements specified in the criteria and the mockup.

- [x] Implement the buttons and their respective redirects.

- [x] Connect to the database to send the new data and receive data stored there.
