### ISSUE TITLE
FR01: Dog's information tab

### ISSUE THREAD

**Issue by EvelynZapata20** [EvelynZapata20/DoggyCare#15]
**Description:** As soon as the user logs in, the system shall provide the user with the ability to visualize its dog's information (by selecting the tab related to the dog's information in the nav bar). 

**Acceptance Criteria:**
- Upon successful login, the default tab shall be the "dogs" tab.
- The “dogs” tab shall display the information of all the registered dogs.
- Each dog's information shall be presented in a card format.
- Each dog's card shall include the following details: photo, name, owner, birthdate, gender, weight and breed.
- Each dog's card shall include buttons to access the following information: Recommendations, Medical Record and Vaccination Card

**Tasks:**
- [x] Create the visual design for the "Dogs" tab, including the dog cards and buttons for recommendations, medical records, and vaccination cards.
- [x] Connect to the data base to extract the  data for all registered dogs.
- [x] Implement functionality for the buttons within each dog card (Recommendations, Medical Record, and Vaccination Card) to navigate the user to the respective sections for each dog.
- [x] Verify that users can access dog information and navigate to recommendations, medical records, and vaccination cards for each dog.
