### ISSUE TITLE
FR04: Owner Verification during Pet Registration

### ISSUE THREAD

**Issue by EvelynZapata20** [EvelynZapata20/DoggyCare#17]
**Description:** During the dog registration process, the system shall verify the dog owner's registration status through the name.

**Acceptance Criteria:**
- Whitin the owner field the system shall provide a list of registered owners.
- The system shall allow vets to input an owner's name during the registration process.
- The system shall validate whether the input document number matches an entry in the registered owners' list.
- If the owner's document number matches an existing entry in the registered owners' list, the staff shall be able to proceed with associating the pet with the corresponding owner.

**Tasks:**
- [x] Implement a mechanism to compare the input name with entries in the registered owners' list to check for a match.
- [x] Develop functionality that allows staff to proceed with associating the pet with the corresponding owner if a match is found between the input document number and an existing entry.
- [x] Test the function.
