### ISSUE TITLE
FR05: Client’s personalized search

### ISSUE THREAD

**Issue by Emanuelpa** [EvelynZapata20/DoggyCare#5]
**Description:** 
The system shall provide the clients with the ability to perform searches based on their dog’s breed, birthdate, and medical history to obtain a list of possible associated diseases or common health issues.

**Acceptance Criteria:**

•	The search by trait tab allows the customer to fill in the breed, birthdate, and medical history fields and get matching results.
•	The breed field will have the available dog breeds for the user to register the one that meets their need. Available dog 
breeds (Labrador Retriever, German Shepherd, Bulldog, Poodle, Siberian Husky, Chihuahua, Golden Retriever, Boxer, 
Rottweiler, Yorkshire Terrier, Beagle, French Bulldog, Dachshund, Shih Tzu, Border Collie, English Bulldog, Cocker Spaniel, 
Doberman Pinscher, Maltese, Shetland Sheepdog, Great Dane, Miniature Schnauzer, Cavalier King Charles Spaniel, Boston 
Terrier, Bull Terrier, Chow Chow, Bullmastiff, Miniature Pinscher, Bichon Frise, Shiba Inu, West Highland White Terrier, Saint 
Bernard, Pomeranian, American Staffordshire Terrier, Bernese Mountain Dog, Australian Shepherd, Jack Russell Terrier, Pug, Dalmatian, Irish Setter.)
•	When the user selects the breed of his dog and confirms the search by this criterion, the common diseases of the selected breed will be displayed on the screen.
•	The age field will only allow you to fill with positive integers
•	If the user enters the age and confirms the search by this criterion, the program will display the common diseases by age on the screen.
•	In the medical history field, the user can freely enter the name of the disease that his dog has suffered before or currently suffers.
•	If the user confirms the search based on the medical history criteria, the program will display the diseases related to or derived from those entered by the user on the screen.
•	If the user selects more than two fields at the same time, the program will display the results that match all the indicated criteria on the screen.
•	The user must enter at least one criterion, otherwise the system will not display any results on the screen.

**Task:**

- [ ] Create the interface with the elements specified in the criteria and the mockup.
- [ ] Implement the buttons and their respective redirects.
- [ ] Create the restrictions in the text fields as indicated by the acceptance criteria.
- [ ] Create the search system according to the elements selected by the user.
- [ ] Connect to the database to send and receive data stored there, such as dog, client, and diseases information.
